language: java

jdk:
  - oraclejdk7

env:
  matrix:
    - TEAMCITY_VERSION='8.1.5'
    - TEAMCITY_VERSION='9.0.3'
    - TEAMCITY_VERSION='9.1.1'

script:
  - ./gradlew clean build -Dteamcity.version=$TEAMCITY_VERSION
